version: "3.9"
services:
  react-frontend:
    image: react-frontend
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_APP_BACKEND_ADDRESS: http://spring-api-image:8080
    networks:
      - spring-network
    depends_on:
      - spring-api-image

  spring-api-image:
    image: spring-api-image:v1
    container_name: spring-api-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/virtualtoken
      SPRING_DATASOURCE_USERNAME: zevaguillo
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - spring-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zevaguillo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: virtualtoken
    networks:
      - spring-network
    volumes:
      - db-volume:/var/lib/postgresql/data # Aquí se especifica la ruta absoluta en el contenedor
networks:
  spring-network:
volumes:
  db-volume:
