spring:
  mvc:
    servlet:
      path: /api/v1

  application:
    name: virtualToken

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-database:5432/virtualtoken
    username: admin
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
