spring:
  mvc:
    servlet:
      path: /api/v1

  application:
    name: "virtualToken"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/virtualtoken
    username: zevaguillo
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
